// Code generated by protoc-gen-go. DO NOT EDIT.
// source: windows.proto

package grpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetUsersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUsersRequest) Reset()         { *m = GetUsersRequest{} }
func (m *GetUsersRequest) String() string { return proto.CompactTextString(m) }
func (*GetUsersRequest) ProtoMessage()    {}
func (*GetUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_003a17a62ebbff76, []int{0}
}

func (m *GetUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersRequest.Unmarshal(m, b)
}
func (m *GetUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersRequest.Marshal(b, m, deterministic)
}
func (m *GetUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersRequest.Merge(m, src)
}
func (m *GetUsersRequest) XXX_Size() int {
	return xxx_messageInfo_GetUsersRequest.Size(m)
}
func (m *GetUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersRequest proto.InternalMessageInfo

type GetUsersResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Username             []string `protobuf:"bytes,2,rep,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUsersResponse) Reset()         { *m = GetUsersResponse{} }
func (m *GetUsersResponse) String() string { return proto.CompactTextString(m) }
func (*GetUsersResponse) ProtoMessage()    {}
func (*GetUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_003a17a62ebbff76, []int{1}
}

func (m *GetUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUsersResponse.Unmarshal(m, b)
}
func (m *GetUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUsersResponse.Marshal(b, m, deterministic)
}
func (m *GetUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUsersResponse.Merge(m, src)
}
func (m *GetUsersResponse) XXX_Size() int {
	return xxx_messageInfo_GetUsersResponse.Size(m)
}
func (m *GetUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUsersResponse proto.InternalMessageInfo

func (m *GetUsersResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *GetUsersResponse) GetUsername() []string {
	if m != nil {
		return m.Username
	}
	return nil
}

type GetHostnameRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHostnameRequest) Reset()         { *m = GetHostnameRequest{} }
func (m *GetHostnameRequest) String() string { return proto.CompactTextString(m) }
func (*GetHostnameRequest) ProtoMessage()    {}
func (*GetHostnameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_003a17a62ebbff76, []int{2}
}

func (m *GetHostnameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHostnameRequest.Unmarshal(m, b)
}
func (m *GetHostnameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHostnameRequest.Marshal(b, m, deterministic)
}
func (m *GetHostnameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHostnameRequest.Merge(m, src)
}
func (m *GetHostnameRequest) XXX_Size() int {
	return xxx_messageInfo_GetHostnameRequest.Size(m)
}
func (m *GetHostnameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHostnameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetHostnameRequest proto.InternalMessageInfo

type GetHostnameResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Hostname             string   `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	ComputerName         string   `protobuf:"bytes,3,opt,name=computer_name,json=computerName,proto3" json:"computer_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHostnameResponse) Reset()         { *m = GetHostnameResponse{} }
func (m *GetHostnameResponse) String() string { return proto.CompactTextString(m) }
func (*GetHostnameResponse) ProtoMessage()    {}
func (*GetHostnameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_003a17a62ebbff76, []int{3}
}

func (m *GetHostnameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHostnameResponse.Unmarshal(m, b)
}
func (m *GetHostnameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHostnameResponse.Marshal(b, m, deterministic)
}
func (m *GetHostnameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHostnameResponse.Merge(m, src)
}
func (m *GetHostnameResponse) XXX_Size() int {
	return xxx_messageInfo_GetHostnameResponse.Size(m)
}
func (m *GetHostnameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHostnameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetHostnameResponse proto.InternalMessageInfo

func (m *GetHostnameResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *GetHostnameResponse) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *GetHostnameResponse) GetComputerName() string {
	if m != nil {
		return m.ComputerName
	}
	return ""
}

type Addrs struct {
	IpAddress            string   `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Subnet               string   `protobuf:"bytes,2,opt,name=subnet,proto3" json:"subnet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Addrs) Reset()         { *m = Addrs{} }
func (m *Addrs) String() string { return proto.CompactTextString(m) }
func (*Addrs) ProtoMessage()    {}
func (*Addrs) Descriptor() ([]byte, []int) {
	return fileDescriptor_003a17a62ebbff76, []int{4}
}

func (m *Addrs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Addrs.Unmarshal(m, b)
}
func (m *Addrs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Addrs.Marshal(b, m, deterministic)
}
func (m *Addrs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Addrs.Merge(m, src)
}
func (m *Addrs) XXX_Size() int {
	return xxx_messageInfo_Addrs.Size(m)
}
func (m *Addrs) XXX_DiscardUnknown() {
	xxx_messageInfo_Addrs.DiscardUnknown(m)
}

var xxx_messageInfo_Addrs proto.InternalMessageInfo

func (m *Addrs) GetIpAddress() string {
	if m != nil {
		return m.IpAddress
	}
	return ""
}

func (m *Addrs) GetSubnet() string {
	if m != nil {
		return m.Subnet
	}
	return ""
}

type GetNetworkConfigRequest struct {
	MacAddress           string   `protobuf:"bytes,1,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNetworkConfigRequest) Reset()         { *m = GetNetworkConfigRequest{} }
func (m *GetNetworkConfigRequest) String() string { return proto.CompactTextString(m) }
func (*GetNetworkConfigRequest) ProtoMessage()    {}
func (*GetNetworkConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_003a17a62ebbff76, []int{5}
}

func (m *GetNetworkConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNetworkConfigRequest.Unmarshal(m, b)
}
func (m *GetNetworkConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNetworkConfigRequest.Marshal(b, m, deterministic)
}
func (m *GetNetworkConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNetworkConfigRequest.Merge(m, src)
}
func (m *GetNetworkConfigRequest) XXX_Size() int {
	return xxx_messageInfo_GetNetworkConfigRequest.Size(m)
}
func (m *GetNetworkConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNetworkConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetNetworkConfigRequest proto.InternalMessageInfo

func (m *GetNetworkConfigRequest) GetMacAddress() string {
	if m != nil {
		return m.MacAddress
	}
	return ""
}

type GetNetworkConfigResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	MacAddress           string   `protobuf:"bytes,2,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	Addrs                []*Addrs `protobuf:"bytes,3,rep,name=addrs,proto3" json:"addrs,omitempty"`
	Gateway              string   `protobuf:"bytes,4,opt,name=gateway,proto3" json:"gateway,omitempty"`
	DnsServer            []string `protobuf:"bytes,5,rep,name=dns_server,json=dnsServer,proto3" json:"dns_server,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetNetworkConfigResponse) Reset()         { *m = GetNetworkConfigResponse{} }
func (m *GetNetworkConfigResponse) String() string { return proto.CompactTextString(m) }
func (*GetNetworkConfigResponse) ProtoMessage()    {}
func (*GetNetworkConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_003a17a62ebbff76, []int{6}
}

func (m *GetNetworkConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetNetworkConfigResponse.Unmarshal(m, b)
}
func (m *GetNetworkConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetNetworkConfigResponse.Marshal(b, m, deterministic)
}
func (m *GetNetworkConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetNetworkConfigResponse.Merge(m, src)
}
func (m *GetNetworkConfigResponse) XXX_Size() int {
	return xxx_messageInfo_GetNetworkConfigResponse.Size(m)
}
func (m *GetNetworkConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetNetworkConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetNetworkConfigResponse proto.InternalMessageInfo

func (m *GetNetworkConfigResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *GetNetworkConfigResponse) GetMacAddress() string {
	if m != nil {
		return m.MacAddress
	}
	return ""
}

func (m *GetNetworkConfigResponse) GetAddrs() []*Addrs {
	if m != nil {
		return m.Addrs
	}
	return nil
}

func (m *GetNetworkConfigResponse) GetGateway() string {
	if m != nil {
		return m.Gateway
	}
	return ""
}

func (m *GetNetworkConfigResponse) GetDnsServer() []string {
	if m != nil {
		return m.DnsServer
	}
	return nil
}

type GetKMSRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetKMSRequest) Reset()         { *m = GetKMSRequest{} }
func (m *GetKMSRequest) String() string { return proto.CompactTextString(m) }
func (*GetKMSRequest) ProtoMessage()    {}
func (*GetKMSRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_003a17a62ebbff76, []int{7}
}

func (m *GetKMSRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetKMSRequest.Unmarshal(m, b)
}
func (m *GetKMSRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetKMSRequest.Marshal(b, m, deterministic)
}
func (m *GetKMSRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetKMSRequest.Merge(m, src)
}
func (m *GetKMSRequest) XXX_Size() int {
	return xxx_messageInfo_GetKMSRequest.Size(m)
}
func (m *GetKMSRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetKMSRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetKMSRequest proto.InternalMessageInfo

type GetKMSResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Server               string   `protobuf:"bytes,2,opt,name=server,proto3" json:"server,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetKMSResponse) Reset()         { *m = GetKMSResponse{} }
func (m *GetKMSResponse) String() string { return proto.CompactTextString(m) }
func (*GetKMSResponse) ProtoMessage()    {}
func (*GetKMSResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_003a17a62ebbff76, []int{8}
}

func (m *GetKMSResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetKMSResponse.Unmarshal(m, b)
}
func (m *GetKMSResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetKMSResponse.Marshal(b, m, deterministic)
}
func (m *GetKMSResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetKMSResponse.Merge(m, src)
}
func (m *GetKMSResponse) XXX_Size() int {
	return xxx_messageInfo_GetKMSResponse.Size(m)
}
func (m *GetKMSResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetKMSResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetKMSResponse proto.InternalMessageInfo

func (m *GetKMSResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *GetKMSResponse) GetServer() string {
	if m != nil {
		return m.Server
	}
	return ""
}

//SetUserPassword
type SetUserPasswordRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	ExpiredTimestamp     string   `protobuf:"bytes,3,opt,name=expired_timestamp,json=expiredTimestamp,proto3" json:"expired_timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetUserPasswordRequest) Reset()         { *m = SetUserPasswordRequest{} }
func (m *SetUserPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*SetUserPasswordRequest) ProtoMessage()    {}
func (*SetUserPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_003a17a62ebbff76, []int{9}
}

func (m *SetUserPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetUserPasswordRequest.Unmarshal(m, b)
}
func (m *SetUserPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetUserPasswordRequest.Marshal(b, m, deterministic)
}
func (m *SetUserPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetUserPasswordRequest.Merge(m, src)
}
func (m *SetUserPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_SetUserPasswordRequest.Size(m)
}
func (m *SetUserPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetUserPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetUserPasswordRequest proto.InternalMessageInfo

func (m *SetUserPasswordRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *SetUserPasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *SetUserPasswordRequest) GetExpiredTimestamp() string {
	if m != nil {
		return m.ExpiredTimestamp
	}
	return ""
}

type SetUserPasswordResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetUserPasswordResponse) Reset()         { *m = SetUserPasswordResponse{} }
func (m *SetUserPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*SetUserPasswordResponse) ProtoMessage()    {}
func (*SetUserPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_003a17a62ebbff76, []int{10}
}

func (m *SetUserPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetUserPasswordResponse.Unmarshal(m, b)
}
func (m *SetUserPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetUserPasswordResponse.Marshal(b, m, deterministic)
}
func (m *SetUserPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetUserPasswordResponse.Merge(m, src)
}
func (m *SetUserPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_SetUserPasswordResponse.Size(m)
}
func (m *SetUserPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetUserPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetUserPasswordResponse proto.InternalMessageInfo

func (m *SetUserPasswordResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

//SetHostname
type SetHostnameRequest struct {
	Hostname             string   `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetHostnameRequest) Reset()         { *m = SetHostnameRequest{} }
func (m *SetHostnameRequest) String() string { return proto.CompactTextString(m) }
func (*SetHostnameRequest) ProtoMessage()    {}
func (*SetHostnameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_003a17a62ebbff76, []int{11}
}

func (m *SetHostnameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetHostnameRequest.Unmarshal(m, b)
}
func (m *SetHostnameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetHostnameRequest.Marshal(b, m, deterministic)
}
func (m *SetHostnameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetHostnameRequest.Merge(m, src)
}
func (m *SetHostnameRequest) XXX_Size() int {
	return xxx_messageInfo_SetHostnameRequest.Size(m)
}
func (m *SetHostnameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetHostnameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetHostnameRequest proto.InternalMessageInfo

func (m *SetHostnameRequest) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

type SetHostnameResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetHostnameResponse) Reset()         { *m = SetHostnameResponse{} }
func (m *SetHostnameResponse) String() string { return proto.CompactTextString(m) }
func (*SetHostnameResponse) ProtoMessage()    {}
func (*SetHostnameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_003a17a62ebbff76, []int{12}
}

func (m *SetHostnameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetHostnameResponse.Unmarshal(m, b)
}
func (m *SetHostnameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetHostnameResponse.Marshal(b, m, deterministic)
}
func (m *SetHostnameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetHostnameResponse.Merge(m, src)
}
func (m *SetHostnameResponse) XXX_Size() int {
	return xxx_messageInfo_SetHostnameResponse.Size(m)
}
func (m *SetHostnameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetHostnameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetHostnameResponse proto.InternalMessageInfo

func (m *SetHostnameResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

//SetNetworkConfigRequest
type SetNetworkConfigRequest struct {
	MacAddress           string   `protobuf:"bytes,1,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	Addrs                []*Addrs `protobuf:"bytes,2,rep,name=addrs,proto3" json:"addrs,omitempty"`
	Gateway              string   `protobuf:"bytes,3,opt,name=gateway,proto3" json:"gateway,omitempty"`
	DnsServer            []string `protobuf:"bytes,4,rep,name=dns_server,json=dnsServer,proto3" json:"dns_server,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetNetworkConfigRequest) Reset()         { *m = SetNetworkConfigRequest{} }
func (m *SetNetworkConfigRequest) String() string { return proto.CompactTextString(m) }
func (*SetNetworkConfigRequest) ProtoMessage()    {}
func (*SetNetworkConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_003a17a62ebbff76, []int{13}
}

func (m *SetNetworkConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetNetworkConfigRequest.Unmarshal(m, b)
}
func (m *SetNetworkConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetNetworkConfigRequest.Marshal(b, m, deterministic)
}
func (m *SetNetworkConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetNetworkConfigRequest.Merge(m, src)
}
func (m *SetNetworkConfigRequest) XXX_Size() int {
	return xxx_messageInfo_SetNetworkConfigRequest.Size(m)
}
func (m *SetNetworkConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetNetworkConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetNetworkConfigRequest proto.InternalMessageInfo

func (m *SetNetworkConfigRequest) GetMacAddress() string {
	if m != nil {
		return m.MacAddress
	}
	return ""
}

func (m *SetNetworkConfigRequest) GetAddrs() []*Addrs {
	if m != nil {
		return m.Addrs
	}
	return nil
}

func (m *SetNetworkConfigRequest) GetGateway() string {
	if m != nil {
		return m.Gateway
	}
	return ""
}

func (m *SetNetworkConfigRequest) GetDnsServer() []string {
	if m != nil {
		return m.DnsServer
	}
	return nil
}

type SetNetworkConfigResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetNetworkConfigResponse) Reset()         { *m = SetNetworkConfigResponse{} }
func (m *SetNetworkConfigResponse) String() string { return proto.CompactTextString(m) }
func (*SetNetworkConfigResponse) ProtoMessage()    {}
func (*SetNetworkConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_003a17a62ebbff76, []int{14}
}

func (m *SetNetworkConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetNetworkConfigResponse.Unmarshal(m, b)
}
func (m *SetNetworkConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetNetworkConfigResponse.Marshal(b, m, deterministic)
}
func (m *SetNetworkConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetNetworkConfigResponse.Merge(m, src)
}
func (m *SetNetworkConfigResponse) XXX_Size() int {
	return xxx_messageInfo_SetNetworkConfigResponse.Size(m)
}
func (m *SetNetworkConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetNetworkConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetNetworkConfigResponse proto.InternalMessageInfo

func (m *SetNetworkConfigResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

//SetKMS
type SetKMSRequest struct {
	Server               string   `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetKMSRequest) Reset()         { *m = SetKMSRequest{} }
func (m *SetKMSRequest) String() string { return proto.CompactTextString(m) }
func (*SetKMSRequest) ProtoMessage()    {}
func (*SetKMSRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_003a17a62ebbff76, []int{15}
}

func (m *SetKMSRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetKMSRequest.Unmarshal(m, b)
}
func (m *SetKMSRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetKMSRequest.Marshal(b, m, deterministic)
}
func (m *SetKMSRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetKMSRequest.Merge(m, src)
}
func (m *SetKMSRequest) XXX_Size() int {
	return xxx_messageInfo_SetKMSRequest.Size(m)
}
func (m *SetKMSRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetKMSRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetKMSRequest proto.InternalMessageInfo

func (m *SetKMSRequest) GetServer() string {
	if m != nil {
		return m.Server
	}
	return ""
}

type SetKMSResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetKMSResponse) Reset()         { *m = SetKMSResponse{} }
func (m *SetKMSResponse) String() string { return proto.CompactTextString(m) }
func (*SetKMSResponse) ProtoMessage()    {}
func (*SetKMSResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_003a17a62ebbff76, []int{16}
}

func (m *SetKMSResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetKMSResponse.Unmarshal(m, b)
}
func (m *SetKMSResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetKMSResponse.Marshal(b, m, deterministic)
}
func (m *SetKMSResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetKMSResponse.Merge(m, src)
}
func (m *SetKMSResponse) XXX_Size() int {
	return xxx_messageInfo_SetKMSResponse.Size(m)
}
func (m *SetKMSResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetKMSResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetKMSResponse proto.InternalMessageInfo

func (m *SetKMSResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*GetUsersRequest)(nil), "grpc.GetUsersRequest")
	proto.RegisterType((*GetUsersResponse)(nil), "grpc.GetUsersResponse")
	proto.RegisterType((*GetHostnameRequest)(nil), "grpc.GetHostnameRequest")
	proto.RegisterType((*GetHostnameResponse)(nil), "grpc.GetHostnameResponse")
	proto.RegisterType((*Addrs)(nil), "grpc.Addrs")
	proto.RegisterType((*GetNetworkConfigRequest)(nil), "grpc.GetNetworkConfigRequest")
	proto.RegisterType((*GetNetworkConfigResponse)(nil), "grpc.GetNetworkConfigResponse")
	proto.RegisterType((*GetKMSRequest)(nil), "grpc.GetKMSRequest")
	proto.RegisterType((*GetKMSResponse)(nil), "grpc.GetKMSResponse")
	proto.RegisterType((*SetUserPasswordRequest)(nil), "grpc.SetUserPasswordRequest")
	proto.RegisterType((*SetUserPasswordResponse)(nil), "grpc.SetUserPasswordResponse")
	proto.RegisterType((*SetHostnameRequest)(nil), "grpc.SetHostnameRequest")
	proto.RegisterType((*SetHostnameResponse)(nil), "grpc.SetHostnameResponse")
	proto.RegisterType((*SetNetworkConfigRequest)(nil), "grpc.SetNetworkConfigRequest")
	proto.RegisterType((*SetNetworkConfigResponse)(nil), "grpc.SetNetworkConfigResponse")
	proto.RegisterType((*SetKMSRequest)(nil), "grpc.SetKMSRequest")
	proto.RegisterType((*SetKMSResponse)(nil), "grpc.SetKMSResponse")
}

func init() { proto.RegisterFile("windows.proto", fileDescriptor_003a17a62ebbff76) }

var fileDescriptor_003a17a62ebbff76 = []byte{
	// 598 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0x5d, 0x8f, 0xd2, 0x4c,
	0x14, 0x4e, 0xf9, 0xd8, 0x77, 0x39, 0xbc, 0xc0, 0xee, 0x80, 0x6c, 0x6d, 0x44, 0xb1, 0x26, 0x4a,
	0xb2, 0x09, 0x6e, 0x76, 0xaf, 0xf4, 0x62, 0x93, 0x55, 0x13, 0x4c, 0x8c, 0x44, 0x19, 0x8d, 0x97,
	0xa4, 0x4b, 0x8f, 0xd8, 0x68, 0x3f, 0x9c, 0x19, 0x44, 0x2f, 0xfc, 0x1b, 0xfe, 0x0b, 0xaf, 0xfc,
	0x83, 0xa6, 0x9d, 0x99, 0x42, 0x0b, 0x54, 0xf4, 0xf2, 0x7c, 0xcc, 0x33, 0x73, 0x9e, 0xe7, 0xe9,
	0x29, 0x34, 0x96, 0x5e, 0xe0, 0x86, 0x4b, 0x3e, 0x8c, 0x58, 0x28, 0x42, 0x52, 0x99, 0xb3, 0x68,
	0x66, 0x1f, 0x43, 0x6b, 0x84, 0xe2, 0x2d, 0x47, 0xc6, 0x27, 0xf8, 0x79, 0x81, 0x5c, 0xd8, 0xcf,
	0xe0, 0x68, 0x95, 0xe2, 0x51, 0x18, 0x70, 0x24, 0x1d, 0xa8, 0x22, 0x63, 0x21, 0x33, 0x8d, 0xbe,
	0x31, 0xa8, 0x4d, 0x64, 0x40, 0x2c, 0x38, 0x5c, 0x70, 0x64, 0x81, 0xe3, 0xa3, 0x59, 0xea, 0x97,
	0x07, 0xb5, 0x49, 0x1a, 0xdb, 0x1d, 0x20, 0x23, 0x14, 0xcf, 0x43, 0x2e, 0xe2, 0x50, 0x63, 0x7f,
	0x82, 0x76, 0x26, 0xfb, 0x27, 0xf8, 0x0f, 0xaa, 0xd3, 0x2c, 0x25, 0x85, 0x34, 0x26, 0xf7, 0xa0,
	0x31, 0x0b, 0xfd, 0x68, 0x21, 0x90, 0x4d, 0x93, 0x86, 0x72, 0xd2, 0xf0, 0xbf, 0x4e, 0x8e, 0xe3,
	0x37, 0x5c, 0x42, 0xf5, 0xca, 0x75, 0x19, 0x27, 0x3d, 0x00, 0x2f, 0x9a, 0x3a, 0xae, 0xcb, 0x90,
	0x73, 0x75, 0x49, 0xcd, 0x8b, 0xae, 0x64, 0x82, 0x74, 0xe1, 0x80, 0x2f, 0xae, 0x03, 0x14, 0xea,
	0x1a, 0x15, 0xd9, 0x8f, 0xe1, 0x64, 0x84, 0x62, 0x8c, 0x62, 0x19, 0xb2, 0x8f, 0x4f, 0xc3, 0xe0,
	0xbd, 0x37, 0x57, 0x83, 0x90, 0x3b, 0x50, 0xf7, 0x9d, 0x59, 0x0e, 0x12, 0x7c, 0x67, 0xa6, 0x30,
	0xed, 0x9f, 0x06, 0x98, 0x9b, 0x87, 0x0b, 0xe7, 0xcd, 0x61, 0x96, 0xf2, 0x98, 0xe4, 0x2e, 0x54,
	0xe3, 0x22, 0x37, 0xcb, 0xfd, 0xf2, 0xa0, 0x7e, 0x5e, 0x1f, 0xc6, 0x12, 0x0e, 0x93, 0x11, 0x27,
	0xb2, 0x42, 0x4c, 0xf8, 0x6f, 0xee, 0x08, 0x5c, 0x3a, 0xdf, 0xcc, 0x4a, 0x72, 0x5e, 0x87, 0x31,
	0x07, 0x6e, 0xc0, 0xa7, 0x1c, 0xd9, 0x17, 0x64, 0x66, 0x35, 0x91, 0xab, 0xe6, 0x06, 0x9c, 0x26,
	0x09, 0xbb, 0x05, 0x8d, 0x11, 0x8a, 0x17, 0x2f, 0xa9, 0x96, 0xea, 0x12, 0x9a, 0x3a, 0x51, 0xf8,
	0xea, 0x98, 0x3c, 0x89, 0xa9, 0xc9, 0x93, 0x80, 0xdf, 0xa1, 0x4b, 0xa5, 0x8d, 0x5e, 0x39, 0x9c,
	0x2f, 0x43, 0xe6, 0x6a, 0xee, 0xd6, 0x6d, 0x23, 0xa1, 0xd2, 0x38, 0xae, 0x45, 0xaa, 0x5d, 0x6b,
	0xae, 0x63, 0x72, 0x0a, 0xc7, 0xf8, 0x35, 0xf2, 0x18, 0xba, 0x53, 0xe1, 0xf9, 0xc8, 0x85, 0xe3,
	0x47, 0x4a, 0xf7, 0x23, 0x55, 0x78, 0xa3, 0xf3, 0xf6, 0x43, 0x38, 0xd9, 0xb8, 0xbe, 0x68, 0x0e,
	0xfb, 0x0c, 0x08, 0xdd, 0x30, 0x6c, 0xc6, 0x83, 0x46, 0xd6, 0x83, 0xf6, 0x29, 0xb4, 0xe9, 0xbe,
	0x66, 0xb6, 0x7f, 0x18, 0xc9, 0x83, 0xfe, 0xc9, 0x4c, 0x2b, 0xe1, 0x4b, 0xfb, 0x08, 0x5f, 0x2e,
	0x12, 0xbe, 0x92, 0x17, 0xfe, 0x0c, 0x4c, 0xfa, 0x57, 0x3e, 0xb5, 0x1f, 0x40, 0x83, 0xae, 0x5b,
	0x65, 0xcd, 0x02, 0x46, 0xc6, 0x02, 0xf7, 0xa1, 0x49, 0xf7, 0xb0, 0xd0, 0xf9, 0xaf, 0x0a, 0x34,
	0xdf, 0xc9, 0xe5, 0x14, 0x3f, 0xca, 0x9b, 0x21, 0x79, 0x04, 0x87, 0x7a, 0x09, 0x91, 0x1b, 0x72,
	0xdc, 0xdc, 0x9e, 0xb2, 0xba, 0xf9, 0xb4, 0xba, 0xe3, 0x09, 0xd4, 0xd7, 0x76, 0x0c, 0x31, 0xd3,
	0xb6, 0x9c, 0xb6, 0xd6, 0xcd, 0x2d, 0x15, 0x85, 0xf1, 0x3a, 0xd9, 0x81, 0x19, 0x52, 0x48, 0x2f,
	0x6d, 0xdf, 0x26, 0xa2, 0x75, 0x7b, 0x57, 0x59, 0x41, 0x5e, 0xc0, 0x81, 0xfc, 0x9e, 0x48, 0x3b,
	0xed, 0x5c, 0x71, 0x68, 0x75, 0xb2, 0x49, 0x75, 0x68, 0x0c, 0xad, 0x9c, 0x8b, 0xc9, 0x2d, 0xd9,
	0xb8, 0xfd, 0xdb, 0xb2, 0x7a, 0x3b, 0xaa, 0x2b, 0x6e, 0xe8, 0x26, 0x37, 0x74, 0x27, 0x37, 0x74,
	0x3b, 0x37, 0x74, 0x07, 0x37, 0xb4, 0x98, 0x1b, 0x5a, 0xc0, 0x0d, 0xcd, 0x70, 0x43, 0xb7, 0x71,
	0x93, 0xf5, 0xd2, 0xf5, 0x41, 0xf2, 0x1f, 0xbb, 0xf8, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x55, 0x58,
	0xa9, 0x3b, 0xd8, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WindowsServiceClient is the client API for WindowsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WindowsServiceClient interface {
	GetUsers(ctx context.Context, in *GetUsersRequest, opts ...grpc.CallOption) (*GetUsersResponse, error)
	GetHostname(ctx context.Context, in *GetHostnameRequest, opts ...grpc.CallOption) (*GetHostnameResponse, error)
	GetNetworkConfig(ctx context.Context, in *GetNetworkConfigRequest, opts ...grpc.CallOption) (*GetNetworkConfigResponse, error)
	GetKMS(ctx context.Context, in *GetKMSRequest, opts ...grpc.CallOption) (*GetKMSResponse, error)
	SetUserPassword(ctx context.Context, in *SetUserPasswordRequest, opts ...grpc.CallOption) (*SetUserPasswordResponse, error)
	SetHostname(ctx context.Context, in *SetHostnameRequest, opts ...grpc.CallOption) (*SetHostnameResponse, error)
	SetNetworkConfig(ctx context.Context, in *SetNetworkConfigRequest, opts ...grpc.CallOption) (*SetNetworkConfigResponse, error)
	SetKMS(ctx context.Context, in *SetKMSRequest, opts ...grpc.CallOption) (*SetKMSResponse, error)
}

type windowsServiceClient struct {
	cc *grpc.ClientConn
}

func NewWindowsServiceClient(cc *grpc.ClientConn) WindowsServiceClient {
	return &windowsServiceClient{cc}
}

func (c *windowsServiceClient) GetUsers(ctx context.Context, in *GetUsersRequest, opts ...grpc.CallOption) (*GetUsersResponse, error) {
	out := new(GetUsersResponse)
	err := c.cc.Invoke(ctx, "/grpc.WindowsService/GetUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *windowsServiceClient) GetHostname(ctx context.Context, in *GetHostnameRequest, opts ...grpc.CallOption) (*GetHostnameResponse, error) {
	out := new(GetHostnameResponse)
	err := c.cc.Invoke(ctx, "/grpc.WindowsService/GetHostname", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *windowsServiceClient) GetNetworkConfig(ctx context.Context, in *GetNetworkConfigRequest, opts ...grpc.CallOption) (*GetNetworkConfigResponse, error) {
	out := new(GetNetworkConfigResponse)
	err := c.cc.Invoke(ctx, "/grpc.WindowsService/GetNetworkConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *windowsServiceClient) GetKMS(ctx context.Context, in *GetKMSRequest, opts ...grpc.CallOption) (*GetKMSResponse, error) {
	out := new(GetKMSResponse)
	err := c.cc.Invoke(ctx, "/grpc.WindowsService/GetKMS", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *windowsServiceClient) SetUserPassword(ctx context.Context, in *SetUserPasswordRequest, opts ...grpc.CallOption) (*SetUserPasswordResponse, error) {
	out := new(SetUserPasswordResponse)
	err := c.cc.Invoke(ctx, "/grpc.WindowsService/SetUserPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *windowsServiceClient) SetHostname(ctx context.Context, in *SetHostnameRequest, opts ...grpc.CallOption) (*SetHostnameResponse, error) {
	out := new(SetHostnameResponse)
	err := c.cc.Invoke(ctx, "/grpc.WindowsService/SetHostname", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *windowsServiceClient) SetNetworkConfig(ctx context.Context, in *SetNetworkConfigRequest, opts ...grpc.CallOption) (*SetNetworkConfigResponse, error) {
	out := new(SetNetworkConfigResponse)
	err := c.cc.Invoke(ctx, "/grpc.WindowsService/SetNetworkConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *windowsServiceClient) SetKMS(ctx context.Context, in *SetKMSRequest, opts ...grpc.CallOption) (*SetKMSResponse, error) {
	out := new(SetKMSResponse)
	err := c.cc.Invoke(ctx, "/grpc.WindowsService/SetKMS", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WindowsServiceServer is the server API for WindowsService service.
type WindowsServiceServer interface {
	GetUsers(context.Context, *GetUsersRequest) (*GetUsersResponse, error)
	GetHostname(context.Context, *GetHostnameRequest) (*GetHostnameResponse, error)
	GetNetworkConfig(context.Context, *GetNetworkConfigRequest) (*GetNetworkConfigResponse, error)
	GetKMS(context.Context, *GetKMSRequest) (*GetKMSResponse, error)
	SetUserPassword(context.Context, *SetUserPasswordRequest) (*SetUserPasswordResponse, error)
	SetHostname(context.Context, *SetHostnameRequest) (*SetHostnameResponse, error)
	SetNetworkConfig(context.Context, *SetNetworkConfigRequest) (*SetNetworkConfigResponse, error)
	SetKMS(context.Context, *SetKMSRequest) (*SetKMSResponse, error)
}

// UnimplementedWindowsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedWindowsServiceServer struct {
}

func (*UnimplementedWindowsServiceServer) GetUsers(ctx context.Context, req *GetUsersRequest) (*GetUsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsers not implemented")
}
func (*UnimplementedWindowsServiceServer) GetHostname(ctx context.Context, req *GetHostnameRequest) (*GetHostnameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHostname not implemented")
}
func (*UnimplementedWindowsServiceServer) GetNetworkConfig(ctx context.Context, req *GetNetworkConfigRequest) (*GetNetworkConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNetworkConfig not implemented")
}
func (*UnimplementedWindowsServiceServer) GetKMS(ctx context.Context, req *GetKMSRequest) (*GetKMSResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKMS not implemented")
}
func (*UnimplementedWindowsServiceServer) SetUserPassword(ctx context.Context, req *SetUserPasswordRequest) (*SetUserPasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetUserPassword not implemented")
}
func (*UnimplementedWindowsServiceServer) SetHostname(ctx context.Context, req *SetHostnameRequest) (*SetHostnameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetHostname not implemented")
}
func (*UnimplementedWindowsServiceServer) SetNetworkConfig(ctx context.Context, req *SetNetworkConfigRequest) (*SetNetworkConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetNetworkConfig not implemented")
}
func (*UnimplementedWindowsServiceServer) SetKMS(ctx context.Context, req *SetKMSRequest) (*SetKMSResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetKMS not implemented")
}

func RegisterWindowsServiceServer(s *grpc.Server, srv WindowsServiceServer) {
	s.RegisterService(&_WindowsService_serviceDesc, srv)
}

func _WindowsService_GetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WindowsServiceServer).GetUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.WindowsService/GetUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WindowsServiceServer).GetUsers(ctx, req.(*GetUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WindowsService_GetHostname_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHostnameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WindowsServiceServer).GetHostname(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.WindowsService/GetHostname",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WindowsServiceServer).GetHostname(ctx, req.(*GetHostnameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WindowsService_GetNetworkConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNetworkConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WindowsServiceServer).GetNetworkConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.WindowsService/GetNetworkConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WindowsServiceServer).GetNetworkConfig(ctx, req.(*GetNetworkConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WindowsService_GetKMS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKMSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WindowsServiceServer).GetKMS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.WindowsService/GetKMS",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WindowsServiceServer).GetKMS(ctx, req.(*GetKMSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WindowsService_SetUserPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUserPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WindowsServiceServer).SetUserPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.WindowsService/SetUserPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WindowsServiceServer).SetUserPassword(ctx, req.(*SetUserPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WindowsService_SetHostname_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetHostnameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WindowsServiceServer).SetHostname(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.WindowsService/SetHostname",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WindowsServiceServer).SetHostname(ctx, req.(*SetHostnameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WindowsService_SetNetworkConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetNetworkConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WindowsServiceServer).SetNetworkConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.WindowsService/SetNetworkConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WindowsServiceServer).SetNetworkConfig(ctx, req.(*SetNetworkConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WindowsService_SetKMS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetKMSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WindowsServiceServer).SetKMS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.WindowsService/SetKMS",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WindowsServiceServer).SetKMS(ctx, req.(*SetKMSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WindowsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.WindowsService",
	HandlerType: (*WindowsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUsers",
			Handler:    _WindowsService_GetUsers_Handler,
		},
		{
			MethodName: "GetHostname",
			Handler:    _WindowsService_GetHostname_Handler,
		},
		{
			MethodName: "GetNetworkConfig",
			Handler:    _WindowsService_GetNetworkConfig_Handler,
		},
		{
			MethodName: "GetKMS",
			Handler:    _WindowsService_GetKMS_Handler,
		},
		{
			MethodName: "SetUserPassword",
			Handler:    _WindowsService_SetUserPassword_Handler,
		},
		{
			MethodName: "SetHostname",
			Handler:    _WindowsService_SetHostname_Handler,
		},
		{
			MethodName: "SetNetworkConfig",
			Handler:    _WindowsService_SetNetworkConfig_Handler,
		},
		{
			MethodName: "SetKMS",
			Handler:    _WindowsService_SetKMS_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "windows.proto",
}
